### ISSUE TITLE
Mobs still spawning

### ISSUE THREAD

**Issue by KeizerKronos** [ttryy/ExtendedBeacon#1]
Some mobs still manage to spawn inside the beacon radius? When mining underground in one corner mobs still kept spawning. only in 1 corner tho which is odd

**Comment by ttryy** [comment]
hey, thank you very much for submitting your issue. I think I found the problem I didn't realize the beacon range is a square column but thought it was a distance from the beacon. That should explain your problem I will fix it as soon as possible.

**Comment by KeizerKronos** [comment]
Many thanks for the fast response!
Any ETA? just so I know when to check up on the plugin :)

sincerely Keizer.

Op zo 10 jan. 2021 om 16:56 schreef TTRyY <notifications@github.com>:

**Comment by ttryy** [comment]
I just did a new commit which should fix your problem 👍

**Comment by KeizerKronos** [comment]
Very much obliged good sir :)

Keizer


Op zo 10 jan. 2021 om 19:01 schreef TTRyY <notifications@github.com>:
