### ISSUE TITLE
Suggested feature: defaults for beacon buffs

### ISSUE THREAD

**Issue by seanth** [ttryy/ExtendedBeacon#2]
It would be very nice if in the config things could be set so a beacon would have defaults when activated.

The use I'm  particularly interested in is to have the beacons default to blocking mob spawning. On the server I help admin, we plan on using the Custom Structures mod, with beacons and pyramids encased in bedrock. That way beacons could spawn in the world, but there'd be no way for players to get in and make it so hostile mobs couldn't spawn.

Being able to set things in the config so any beacon starts out blocking mob spawns would be super useful

EDIT: working version of proposed feature in pull request "https://github.com/ttryy/ExtendedBeacon/pull/3"

**Comment by ttryy** [comment]
Sorry for the late response! Thanks for your submission I merged your pull request. I will update the spigot page shortly 😄
